version: '3.7'
services:
    nodered:
        container_name: nodered
        image: nodered/node-red
        ports:
            - "1880:1880"

        environment:
            TZ: America/Lima
        volumes:
            - "./nodered-data:/data"
        privileged: true
        restart: "always"

        network_mode: "host"
            

        # networks:
        #     - connect_network

    db:
        image: lscr.io/linuxserver/mariadb
        container_name: mariadb
        volumes:
        - ./mariadb-data:/config
        privileged: true
        restart: always
        ports:
        - 3306:3306
        environment:
            PUID: 1000
            PGID: 1000
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_mysql
            TZ: America/Lima
         
            
            
    
        secrets:
            - db_password
            - db_root_password
        # networks:
        #     - connect_network    

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt

# networks:
#   connect_network:
